### ISSUE TITLE
An error when changing from "window" to "window-chunk"

### ISSUE THREAD

**Issue by frankdarkluo** [nlpir2020/MIE-ACL-2020#2]
When I change "data.add_raw('train', './data/train.json', 'window)" to "data.add_raw('train', './data/train.json', 'window-chunk')" in line 31,32,33 in util.py, an error occurs as follows:

> `Epoch 1::   0%|                                                                                                                                                         | 0/370 [00:00<?, ?it/s]

> Traceback (most recent call last):
> File "main.py", line 54, in <module>
>   location=args.location)
>  File "/home/guoqing/MIE-ACL-2020/src/model.py", line 304, in train
>   self.keep_p: self.params['keep_p']
>  File "/home/guoqing/anaconda3/envs/tf1/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line > 956, in run
    run_metadata_ptr)
>  File "/home/guoqing/anaconda3/envs/tf1/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1156, in _run
>   (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
> ValueError: Cannot feed value of shape (35, 100) for Tensor 'Placeholder:0', which has shape '(?, ?, 100)'`

Does anyone know how to solve it?

**Comment by nlpir2020** [comment]
Fixed. New version updated.
